### ISSUE TITLE
Course - Single: W3C Errors

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/SMS-Training-Institute#121]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fsms-training-imp.stage.titanweb.com.au%2Fproducts%2Fproduct-category-1%2Fproduct-sub-category-1%2Fproduct-inner-sub-category-title-goes-here-for-this-long-title-goes-here-for-this-long%2Fproduct-complete-title-goes-long-title-goes-long-title-goes-long-title-goes-long-title-goes-long%2F

**Comment by mikay-titan** [comment]
plugin issue
