### ISSUE TITLE
Course Single: Titan Read Slide overlapped to the product thumbnail.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/SMS-Training-Institute#155]
URL: http://sms-training-imp.stage.titanweb.com.au/products/product-category-1/product-sub-category-1/product-inner-sub-category-title-goes-here-for-this-long-title-goes-here-for-this-long/product-complete-title-goes-long-title-goes-long-title-goes-long-title-goes-long-title-goes-long/

![image](https://cloud.githubusercontent.com/assets/12888048/16104705/3013127e-33b6-11e6-8540-637c8a90aa16.png)

**Comment by mikay-titan** [comment]
Note: removed product thumbnail since it's not found in the design
