### ISSUE TITLE
Course Single: There's no padding or margin between thumbnail wrapper.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/SMS-Training-Institute#157]
Reference: https://knowledgebase.titanweb.com.au/implementation/advanced-custom-fields-implementation/woocommerce-product-images

![image](https://cloud.githubusercontent.com/assets/12888048/16104908/eb708aa0-33b7-11e6-95a8-0ca00e49d30d.png)

**Comment by mikay-titan** [comment]
Note: removed product thumbnails as it is not found in the design
