### ISSUE TITLE
Homepage - Testimonials: If there's no featured post, display the latest testimonial post

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/SMS-Training-Institute#190]
![image](https://cloud.githubusercontent.com/assets/12888048/16262633/05b40d98-38a3-11e6-921f-de9605735ede.png)

**Comment by mikay-titan** [comment]
Not a bug. It doesn't state on the scope that we need to display the latest testimonial post if there's no feature post. Note: There is an instruction that you need to select a post to be featured in the homepage.

**Comment by romatitan** [comment]
Instead of displaying the latest testimonial post, the section title was hidden if there's no featured testimonial post.
