### ISSUE TITLE
Custom Fields - Homepage: The label is confusing if it is for Form shortcode or Form title. Rename the field label to "Homepage Form Title". 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/SMS-Training-Institute#5]
**Note:** *bug + * enhancement labels: This is an enhancement that needs attention. 

![image](https://cloud.githubusercontent.com/assets/12888048/15698935/c5c96b40-27fb-11e6-854f-2c50d535f473.png)

**Comment by mikay-titan** [comment]
added instruction in the custom field
