### ISSUE TITLE
Do we need to use 2 fields for youtube or video? 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/SMS-Training-Institute#8]
![image](https://cloud.githubusercontent.com/assets/12888048/15699058/b4cfcda6-27fc-11e6-8041-f01a8d260803.png)

**Comment by mikay-titan** [comment]
2nd field is use for the social media icons found in top header. it links to the YouTube Channel of the user. Homepage video is using the 1st YouTube field as well as the sidebar
